run.sh
The `git rev-list` searches through all the branches, so it might pick up `tag` from another branch leading to invalid SHA.
=> fix(git): replace rev-list with abbrev

dist/index.js, find-successful-workflow.js, package-lock.json, package.json
When working with NX, I want to be able to build everything to a new namespace if there has never been a build on that branch before.
I should already be able to do this using:
```
main-branch-name: ${{ github.ref_name }}
```
However I only have the option to error if there have been no builds on this branch before.
By outputting this information if none are found, I can then use a conditional later on in my workflow to build everything (or specific projects). NX will then deploy what I want to the new namespace.
Open to input as I'm not sure if what I've done here is best practise, for example we don't set the output to false anywhere else for example. I'm unfamiliar with custom github actions
=> Added output to indicate when no previous build was found on this branch

action.yml
This output was added to the code a while ago via PR #16 , however I didn't realise it should probably be added to the actual action.yml in order to be consistent with the others
Not sure if this should also maybe be added to the readme, perhaps with example implementations like using a simple if to decide if to run `nx affected` or `nx run-many`, or something more advanced like using it with [this action](https://github.com/marketplace/actions/conditional-value-for-github-action) to use a hardcoded sha instead of the HEAD~1 that it defaults to.
=> Add missing possible output to action.yml

find-successful-workflow.js
Solves https://github.com/nrwl/nx-set-shas/issues/19
On release workflow runs seem to not have any branch property associated with them, thus the filter on branch creates a bug (no run is found):
=> fix: remove branch filter in runs search when event is of type release

README.md
=> docs: GH Actions use read for actions permission

action.yml, package.json
Composite run steps have had support for conditions [since November 9th, 2021](https://github.blog/changelog/2021-11-09-github-actions-conditional-execution-of-steps-in-actions/).
=> refactor: use run step condition

action.yml, dist/index.js, find-successful-workflow.js, package.json
- Use the core API for reading input parameters to remove dependency on argument order in the Node.js script
- Escape user inputs in shell commands to prevent script injections
- Pass the GitHub token as an environment variable instead of a command line argument to decrease the risk of token leaks
- Use the core API for logging to decrease the risk of secret leaks
=> refactor: escape user input to prevent script injection

.github/workflows/integration-test-workflow.yml, .github/workflows/test-integration.yml, .github/workflows/test.yml, README.md, dist/index.js, find-successful-workflow.js, package-lock.json, package.json
Includes first set of tests. 
Includes https://github.com/nrwl/nx-set-shas/pull/52 necessary for checks on push.
This results in unfortunate breaking changes for some folks (https://github.com/nrwl/nx-set-shas/issues/57#issuecomment-1234289104)
The test set should be expanded later to ensure we check different scenarios.
This is to be investigated as it might need to include a controlled git sub repo.
Related to #62
BREAKING CHANGE
=> fix!: always resolve SHA against provided main branch

dist/index.js, package-lock.json, package.json
setOutput was changed and the old version  triggers deprecation warnings
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> fix: bump @actions/core to 1.10.0

action.yml, find-successful-workflow.js
=> fix: avoid command injection and pass arguments securely

dist/index.js, find-successful-workflow.js
Fixes https://github.com/nrwl/nx-set-shas/issues/83
When a workflow is running with the `pull_request` event, and the change is already merged on the main branch, the BASE SHA is incorrectly recovered with `git merge-base`. This is because the best common ancestor to the current commit is itself, so you always end up with the same commit SHA on BASE and HEAD.
This propose following the regular path to fetch the BASE SHA if it is a `pull_request` event and its payload indicates it has already been merged.
=> fix: support pull_request events that are already merged

dist/index.js, find-successful-workflow.js, package.json
Motivation:
nx-set-shas lacks support for github's [merge queues](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#about-merge-queues)
Modification:
- when `eventName === 'merge_group'` and `merge-queue-base-from-pr` input set to `true`, set the `BASE_SHA` to the `merge-base` of the the default branch + PR's branch
Notes / disclaimer:
- extracting the PR's ref is a little brittle at the moment, since the `merge_group` webhook payload does not include it explicitly
- raised a request to github to include more metadata in the payload: https://github.com/orgs/community/discussions/62219
- using `merge-queue-base-from-pr` on merge queues with the limit set greater than 1 is not recommended (will …
=> feat: add support for merge queues (merge_group events)

README.md, package.json
The document this link points to no longer exists.
Fixes #93
=> docs: remove dead link to nx.dev

dist/index.js, find-successful-workflow.js, package.json
=> fix: fix broken merge group

README.md, dist/index.js, dist/licenses.txt, find-successful-workflow.ts, package.json, yarn.lock
Environment variables which control using a proxy for https requests are respected.
`HTTPS_PROXY` defines the server to proxy requests through
`NO_PROXY` excludes certain domains from the proxy server
=> fix: support https proxy env variables

package.json
The previous release didn't set the version properly
=> chore: set version in package.json to match major

README.md, package.json
=> docs: add info about self hosted runner

dist/index.js, find-successful-workflow.ts, package.json
When the diff between NX_BASE & NX_HEAD is bigger than 30 commits the `commitExests` returns false, because it checks only last 30 commits inside the target branch. It happens because `GET /repos/{owner}/{repo}/commits` has default `per_page` value of 30.
In our workflow, a few times a week we have the diff ~50 commits since the last successful run. As the result `nrwl/nx-set-shas` can't find NX_BASE correct and returns `HEAD~1`.
=> fix: fix commitExists() function for diff bigger than 30 commits

README.md, action.yml, dist/index.js, find-successful-workflow.ts
Solves #97
Introduces the option for the user to provide a fallback sha if no successful run is found.
=> feat(action): fallback sha option

dist/index.js, find-successful-workflow.ts, package.json
Update the BASE to be the empty git tree hash (the result of `git hash-object -t tree /dev/null` or `4b825dc642cb6eb9a060e54bf8d69288fbee4904`), in the case where HEAD~1 doesn't exist.
Demo: https://github.com/mandarini/text-shas-2/actions/runs/10612117442/job/29413110625
=> feat: set NX_BASE to empty tree hash if HEAD~1 does not exist

action.yml, package.json
The `fallback-sha` is listed as a valid input on the github composite action but never passed (#158) to the javascript running behind the scenes. This PR extracts the `fallback-sha` from the github inputs and passes it to the list of arguments.
**Linked Issues:**
- #166
- #158
> [!IMPORTANT]
> This PR is most likely to be ignored if PR #163 is being merged. 
I tested this update in a private repo and it seems to be working just fine.
=> Add missing "fallback-sha" to list of arguments

.github/workflows/test-integration.yml, dist/index.js, find-successful-workflow.ts
**Context**
As reported in #140, the current solution for merge-queue works only when the queue size 1. When more commits are added to the queue, the action keeps setting the same `NX_BASE` for all of them.
**Problem**
When new commits are added to the queue, we expect the `NX_BASE` commit to be the last commit in the queue. However, it sets the last commit in master. _This image from https://github.com/nrwl/nx-set-shas/issues/140#issue-2110155589 represents well the problem._
**Solution proposed**
The `NX_BASE` commit should be main branch HEAD commit when merge-queue has size 1. When size > 1, `NX_BASE` should be the HEAD commit of the last merge branch that current commit is on top of.
Fixes #140
=> fix: return correct NX_BASE SHA for merge_group event

README.md, action.yml, dist/index.js, find-successful-workflow.ts
=> feat: add option to set custom remote
